# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('ufname', models.CharField(db_column='uFName', max_length=100)),
                ('ulname', models.CharField(db_column='uLName', max_length=100)),
                ('uid', models.AutoField(db_column='uId', primary_key=True, serialize=False)),
                ('udob', models.DateField(db_column='uDOB')),
                ('uemailid', models.CharField(blank=True, db_column='uEmailId', max_length=250, null=True)),
                ('uimg', models.CharField(db_column='uImg', max_length=1000)),
            ],
            options={
                'db_table': 'UserProfile',
                'managed': False,
            },
        ),
    ]
