# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uProfile', '0003_auto_20171020_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(db_column='qHead', max_length=120)),
                ('question', models.TextField(db_column='question')),
                ('img', models.CharField(db_column='qImg', max_length=200)),
                ('type', models.CharField(db_column='qtype', max_length=100)),
            ],
            options={
                'db_table': 'QandA',
                'managed': True,
            },
        ),
    ]
