# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uProfile', '0004_qanda'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'answer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(db_column='option', max_length=200)),
            ],
            options={
                'db_table': 'options',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='qanda',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='options',
            name='qId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uProfile.QandA'),
        ),
        migrations.AddField(
            model_name='answer',
            name='aId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uProfile.QandA'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uProfile.options'),
        ),
    ]
