# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uProfile', '0005_auto_20171020_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uimg',
            field=models.ImageField(db_column='uImg', max_length=1000, upload_to=b''),
        ),
    ]
