# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uProfile', '0006_auto_20171031_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uProfile.QandA')),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uProfile.Comments')),
                ('replyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
