# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uProfile', '0007_comments_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanda',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
