# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uProfile', '0010_auto_20171105_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
